### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by LeeThompson** [LeeThompson/lifeplayQOL#1]
### Overview

This is a simple module for LifePlay with the following goals.
* Make a richer experience for players
* Add bug fixes to existing content, where appropriate.  (Later versions of this module will remove any fixes applied to the base game)
* Add tweaks to improve the experience for players.

### Planned Features
* Move between rooms within your house, office, etc.
* Hire a contractor to add, modify or remove rooms (from a pre-created list).  This includes having a backyard.
* Actor Variables set to track the player character's room location for other modders to use.
* **Tweaks!**  Eating a snack at home should not take 10 to 20 minutes, etc.
* **Bug fixes!**  Where possible, if a LifePlay scene has issues, fixes will be attempted.  To take advantage of this, this needs to always be last in the load order!

### Release Plan
* When code complete and tested, docs will be finished and a release package (with all the right folder names) will be published.

## Current State
* Design and prototyping

-----
### Customization
- [ ] Add/Modify Rooms

#### Home
- [x] Move between rooms at home
- [x] Move to backyard
- [x] Move back inside **(not working)**
- [ ] Add ability to hire contractor to add/remove rooms at home

#### Dentist
- [ ] Bathroom (New Room)
- [ ] Office
- [ ] Waiting Room (New Room)

#### Doctor
- [ ] Bathroom (New Room)
- [ ] Examination Room
- [ ] Waiting Room (New Room)

#### Hotel
- [ ] Lobby
- [ ] Lobby Bathroom (New Room)
- [ ] Hotel Room (New Room)
- [ ] Hotel Room Bathroom (New Room)

#### Hospital
- [ ] Front Desk (Modification of Current)
- [ ] Bathroom (New Room)
- [ ] Examination Room (New Room)
- [ ] Hospital Room (New Room)
- [ ] Waiting Room (New Room)

#### Office
- [ ] Bathroom (New Room)
- [ ] Boss's Office (New Room)
- [ ] Main Room

#### Residences
- [ ] Bathroom
- [ ] Bedroom
- [ ] Kitchen
- [ ] Living Room

#### Beach
- [ ] Changing Room (New Room)
- [ ] Restroom (New Room)
- [ ] Camping Tent Interior (New Room, tricky given limited models)

-----
##### vin_Base
- [ ] Fix for `sr_fso_work_dare*`
- [ ] Map for `neighbourhood_bbq`
- [ ] Fix for `AI\high_priority\grocery.lpai`

#### vin_Netori
- [x] Fix for `boss_errand_child`

#### vin_NTR
- [ ] Fix for `boss_asks_impregnant_cms` 

#### vin_Pregnancy
- [x] Fix for `pregnancy_cheat_f` 
- [ ] Fix for `NPC_gives_birth`

#### Third Party 
- [ ] Fix for `gf_suggests_cms`

-----
## Tweaks
- [ ] Meals & Snacks while "in" should take much less time
